# Generated by Django 5.0 on 2023-12-16 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TodoAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="TodoAPI.userprofile"
            ),
        ),
    ]
