# Generated by Django 5.0 on 2023-12-17 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TodoAPI", "0002_alter_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="subtasks",
        ),
    ]
