# Generated by Django 5.0 on 2023-12-17 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TodoAPI", "0003_remove_task_subtasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="TodoAPI.task",
            ),
        ),
    ]
